# disable sudo for container build.
sudo: false

# Enabling test on Linux and OS X
os:
  - linux
  - osx

osx_image: xcode8

# Use Build Matrix to do lint and build seperately
env:
  matrix:
    # code lint
    - TASK=lint
    # r package test
    - TASK=r_test
    # python package test
    - TASK=python_test
    - TASK=python_lightweight_test
    # java package test
    - TASK=java_test
    # cmake test
    - TASK=cmake_test
    # c++ test
    - TASK=cpp_test
  global:
    - secure: "nrpxVaCT+UZ5IoSysFwl4VAOlceZxtgAQ0b66L5e54UbBnCSCaJxyV0AgLcIV4dHAWUmw2yHv+G1jEEUBBcruW+ReTR0RxzZ/widWn8lPJufzANzsprJPCMwNyDch1HfO8JAcwDDm88di9aJkQiodjLojofc4f2PlHovy6HnizUVbjH55mp/XL12n+funT0dWEMX3TikM6g1G8BRT6Djx/HXHFtpMnPl7mY6hjgWLqYIEZwl9qS1MZelajYqCjeEhkQ3ZPyAKT5jDKKYCwHlf2cjPA/jTS6/4S7XipzMdIrelTHbP5Lu02tyPi19liQnA+VbXIa8I6tS2GON27G61tqVdZI2bEJ2CzaW0YEMAlb85VjdPQRFJxwjrkvKjqMlngqi8eEZ5cUW9p4bSQQhZu22X9IAjpbtGB/OiUdwuIq55l5jF4aPECEux78CRGuVarm0KK2Cvs6Ug5c4dv1icRUV+IvTqnr+JLfz7dzFP1unLnFkGNGZfLc3hXtIbdyb+jUvA6nG0botLWgikw4WqQ2HpzBabry7HWZ0DoE71zBBO562boVWbvQNUI5+rjirRnY4F9MECMOJYjRfAX6caQtxWg72PCByOhjgRECYRFBAcEqUiZHau4FAIxYmUMq4rWl2M+Kv9NmFlTKkuqxLfC5rIcziILjhreNXfxyi+s0="
matrix:
  exclude:
    - os: osx
      env: TASK=lint
    - os: osx
      env: TASK=cmake_test
    - os: linux
      env: TASK=r_test
    - os: osx
      env: TASK=python_lightweight_test
    - os: osx
      env: TASK=cpp_test

# dependent apt packages
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - george-edison55-precise-backports
    packages:
      - cmake
      - cmake-data
      - doxygen
      - wget
      - libcurl4-openssl-dev
      - unzip
      - graphviz
      - gcc-4.8
      - g++-4.8
  coverity_scan:
    project:
      name: "shaong/xgboost"
      description: "Build submitted via Travis CI"
    notification_email: cshaong@outlook.com
    build_command_prepend: "./configure; make clean"
    build_command:   "make -j 4"
    branch_pattern: coverity_scan

before_install:
  - source dmlc-core/scripts/travis/travis_setup_env.sh
  - export PYTHONPATH=${PYTHONPATH}:${PWD}/python-package
  - echo "MAVEN_OPTS='-Xmx2048m -XX:MaxPermSize=1024m -XX:ReservedCodeCacheSize=512m -Dorg.slf4j.simpleLogger.defaultLogLevel=error'" > ~/.mavenrc
  - echo -n | openssl s_client -connect scan.coverity.com:443 | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' | sudo tee -a /etc/ssl/certs/ca-
install:
  - source tests/travis/setup.sh

script:
  - tests/travis/run_test.sh

cache:
  directories:
    - ${HOME}/.cache/usr
    - ${HOME}/.cache/pip

before_cache:
  - dmlc-core/scripts/travis/travis_before_cache.sh

after_failure:
  - tests/travis/travis_after_failure.sh

after_success:
  - tree build
  - bash <(curl -s https://codecov.io/bash) -a '-o src/ src/*.c'

notifications:
  email:
    on_success: change
    on_failure: always
